services:
  ui:
    build: 
      context: .
      dockerfile: docker/Dockerfile.ui
    ports:
      - "5173:5173" 
    environment:
      - VITE_WS_URL=${VITE_WS_URL}
  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    