FROM node:22-alpine

WORKDIR /usr/src/app

COPY ./ui/package.json ./package.json
COPY ./ui/package-lock.json ./package-lock.json

RUN npm install 
RUN npm install -g serve

COPY ./ui/ ./
ENV VITE_WS_URL=wss://xoxo.asxcode.com/ws/

RUN npm run build 

EXPOSE  5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

